export type Article = {
  titulo: string;
  marca: string;
  modelo: string;
  detalles: string;
  precio: string;
  imagen1: string;
  imagen2: string;
  imagen3: string;
  imagen4: string;
  imagen5: string;
  imagen6: string;
  id?: string;
  slug: string;
  comentarios: string;
  linkMercadoLibre?: string;
  linkFacebook?: string;
  vendido?: boolean;
  pausado?: boolean;
  valorNuevo?: string;
};
